<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SanPham;

class SanPhamSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id_sanpham' => 1,
                'tensp' => 'Túi mini GG Marmont',
                'anhsp' => 'frontend/upload/CSbNOaunklf0NDNNJH1eQ9RILe9B647zRPYOn4BL.jpg',
                'giasp' => 31250000,
                'mota' => '• Có hình trái tim, chiếc túi mini GG Marmont có hình bóng vui tươi bằng da Gucci Rosso Ancora đỏ matelassé chevron mềm mại. Thiết kế nhỏ gọn được hoàn thiện bằng phần cứng Double G đặc trưng với tông màu vàng nhạt.\r\n• Da Gucci Rosso Ancora đỏ matelassé chevron\r\n• Phần cứng tông màu vàng nhạt\r\n• Lớp lót taffeta đỏ\r\n• Double G\r\n• Bên trong: 1 khe cắm thẻ\r\n• Tay cầm có độ dài 3,1\"\r\n• Dây đeo vai có thể tháo rời và điều chỉnh được với độ dài 18,9\"\r\n• Khóa kéo\r\n• Trọng lượng: Khoảng 0,36lbs\r\n• W5,3\" x H4,5\" x D1\"\r\n• Sản xuất tại Ý\r\n• Phù hợp với Airpods và son môi',
                'giamgia' => 2,
                'giakhuyenmai' => 30625000,
                'soluong' => 10,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 2,
                'tensp' => 'Túi Gucci Bamboo Diva',
                'anhsp' => 'frontend/upload/95kNC4QMu8fgh4Az8ftrikVbxs1StfX9FjUNg3Ui.jpg',
                'giasp' => 130000000,
                'mota' => 'Trong bộ sưu tập Xuân Hè 2025, chiếc túi xách quai xách nhỏ này tái hiện phần cứng tre đặc trưng với các chi tiết bằng đồng thau và men. Gucci Bamboo Diva là điểm nhấn cho mọi phong cách.\r\n• Da bóng màu xanh lá cây rừng\r\n• Phần cứng hình tre tráng men với chi tiết bằng đồng thau\r\n• Cấu trúc 3 miếng ghép\r\n• Lớp lót bằng da màu xanh lá cây rừng\r\n• Bên trong: 1 túi có khóa kéo, gương và túi có thể tháo rời\r\n• Tay cầm dài 4\"\r\n• Dây đeo bằng da có thể tháo rời và điều chỉnh với độ dài 19,7\"; Chiều dài: 39\"-45,7\"\r\n• Khóa hình tre\r\n• 10,5\"W x 5,1\"H x 3,1\"D\r\n• Trọng lượng: xấp xỉ 0,9kg\r\n• Sản xuất tại Ý\r\n• Phù hợp với iPhone Pro Max/Plus, Airpods, ví dài và son môi',
                'giamgia' => 5,
                'giakhuyenmai' => 123500000,
                'soluong' => 10,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 3,
                'tensp' => 'Túi mini Gucci Bamboo Diva',
                'anhsp' => 'frontend/upload/iYz8TkTBrtkLDfsSCTax6JP4gQqBsqN1wfffJ3i1.jpg',
                'giasp' => 130000000,
                'mota' => 'Trong bộ sưu tập Xuân Hè 2025, Gucci Bamboo 1947 giới thiệu các chi tiết tông màu với quai xách và khóa bằng da hình tre. Kiểu dáng này cũng có thể đeo chéo hoặc đeo qua vai.\r\n• Gucci Rosso Ancora da mềm màu đỏ\r\n• Phần cứng tông vàng nhạt\r\n• Cấu trúc 3 miếng ghép\r\n• Lớp lót bằng da đỏ Gucci Rosso Ancora\r\n• Bên trong: 1 túi có khóa kéo, gương và túi có thể tháo rời\r\n• Tay xách bằng da hình tre có độ dài 4,3\"\r\n• Dây đeo bằng da có thể tháo rời và điều chỉnh: Độ dài 21,7\"; chiều dài: 39\" - 43,7\"\r\n• Khóa xách hình tre\r\n• 8,3\"W x 5,9\"H x 2,8\"D\r\n• Trọng lượng: xấp xỉ 1,8lbs\r\n• Sản xuất tại Ý\r\n• Phù hợp với iPhone Pro Max/Plus, Airpods, ví dài và son môi',
                'giamgia' => 5,
                'giakhuyenmai' => 123500000,
                'soluong' => 11,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 4,
                'tensp' => 'Túi Tote GG Emblem',
                'anhsp' => 'frontend/upload/uNJERAtoXUfztG3m7MNZwBMxbZb8fB7DDzAqAA8r.jpg',
                'giasp' => 57250000,
                'mota' => 'Bộ sưu tập GG Emblem tái hiện lịch sử thanh lịch và thủ công của Nhà. Chiếc túi tote này có các khía đánh số trên quai xách có thể điều chỉnh, lấy cảm hứng từ thế giới cưỡi ngựa.\r\n• Vải phủ GG Monogram mới màu be và nâu sẫm\r\n• Viền da màu xanh nhạt với đường khâu tương phản\r\n• Phần cứng tông vàng nhạt\r\n• Lớp lót bằng vải cotton Web màu xanh lá cây và đỏ\r\n• Mặt dây chuyền túi được hiển thị được bán riêng và không bao gồm trong túi xách.\r\n• Khoen chữ D bổ sung cho các vật dụng có thể tháo rời\r\n• Các khía đánh số trên quai xách có thể điều chỉnh; độ dài: 8,5\" - 12,4\"\r\n• Bên trong: 2 ngăn và 1 ngăn khóa kéo ở giữa\r\n• Khóa bấm từ tính\r\n• Rộng 15\" x Cao 9,8\" x Sâu 5,9\"\r\n• Trọng lượng: 0,5 kg\r\n• Sản xuất tại Ý\r\n• Phù hợp với iPhone Pro Max/Plus, Airpods, ví dài và son môi',
                'giamgia' => 2,
                'giakhuyenmai' => 56105000,
                'soluong' => 15,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 5,
                'tensp' => 'Túi GG Marmont medium shoulder',
                'anhsp' => 'frontend/upload/rLbIoZpjpWDOHYzaLnyltTmOsREart2ZA5XdPyRr.jpg',
                'giasp' => 71250000,
                'mota' => 'GG Marmont, bộ sưu tập đặc trưng của Nhà mốt, có phần cứng Double G, dây đeo xích nhiều mặt và kết cấu mềm mại bằng da cực kỳ dẻo dai. Túi sau bóng bẩy mang đến nét chức năng cho kích thước trung bình và lớn.\r\n• Da cừu hình chữ V matelassé màu trắng\r\n• Phần cứng tông vàng nhạt\r\n• Lớp lót viscose đỏ Gucci Rosso Ancora\r\n• Double G\r\n• Bên trong: 1 túi khóa kéo\r\n• Bên ngoài: 1 túi mở\r\n• Dây xích trượt có thể đeo như dây đeo vai với độ dài 22\"\r\n• Vạt có khóa lò xo\r\n• 10,2\" x 5,9\" x 2,8\"\r\n• Trọng lượng: Khoảng 0,6kg\r\n• Sản xuất tại Ý\r\n• Phù hợp với iPhone Pro Max/Plus, Airpods, ví dài và son môi',
                'giamgia' => 5,
                'giakhuyenmai' => 67687500,
                'soluong' => 10,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 6,
                'tensp' => 'Túi Woven mini bucket',
                'anhsp' => 'frontend/upload/vn9TMmXqBX8CM5hkG29ca9fvy9kYYjs8YTSDiVQw.jpg',
                'giasp' => 57500000,
                'mota' => 'Túi được làm nổi bật với chi tiết raffia độc đáo và viền da mịn, gợi nhớ đến phong cách thời tiết ấm áp. Chiếc túi bucket mini này được chế tác từ vải viscose mô phỏng hiệu ứng raffia tự nhiên và được hoàn thiện với miếng da trang trí biểu tượng Double G ở mặt trước.\r\n• Chất liệu viscose mô phỏng raffia tự nhiên\r\n• Viền da màu nâu\r\n• Phụ kiện kim loại màu vàng nhạt\r\n• Lót bằng vải lanh cotton màu nâu\r\n• Miếng da biểu tượng Double G\r\n• Dây đeo dạng dây thừng có thể đeo vai (dài 12.6\") hoặc xách tay (dài 6.7\")\r\n• Kích thước: Rộng 7.1\" x Cao 6.9\" x Sâu 5.5\"\r\n• Trọng lượng: khoảng 0.77 lbs (~ 350g)\r\n• Sản xuất tại Ý\r\n• Đựng vừa iPhone Plus, AirPods, ví và son môi',
                'giamgia' => 2,
                'giakhuyenmai' => 56350000,
                'soluong' => 9,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 7,
                'tensp' => 'Túi GG Emblem medium bucket',
                'anhsp' => 'frontend/upload/8f0VoPTzETFmoKn1ku2ZT02IIsNVXlZ3CDB36tkK.jpg',
                'giasp' => 72500000,
                'mota' => 'Bộ sưu tập GG Emblem mới tái hiện lại nét thanh lịch và sự tinh xảo trong di sản chế tác của thương hiệu. Chiếc túi bucket này nổi bật với thiết kế tiện dụng gồm hai ngăn chính lót vải cotton Web và một ngăn kéo khóa ở giữa.\r\nThông tin chi tiết:\r\n• Vải canvas phủ lớp chống thấm GG Monogram mới màu be và nâu đậm\r\n• Viền da màu nâu với đường chỉ may tương phản\r\n• Lớp lót bên trong bằng vải cotton Web màu xanh lá và đỏ\r\n• Móc trang trí túi trong hình được bán riêng và không đi kèm với túi\r\n• Bên trong: 2 ngăn chính và 1 ngăn có khóa kéo ở giữa\r\n• Chiều dài tay cầm: 7 inch \r\n• Dây đeo da có thể điều chỉnh: độ dài từ 21.2\" – 23.6\", chiều dài tổng: 41.3\" – 42.5\" \r\n• Trọng lượng: khoảng 0.68 kg\r\n• Kích thước: Rộng 9.8\" x Cao 9.8\" x Sâu 5.9\"\r\n• Sản xuất tại Ý\r\n• Đựng vừa iPhone Pro Max/Plus, AirPods, ví dài và son môi',
                'giamgia' => 2,
                'giakhuyenmai' => 71050000,
                'soluong' => 10,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 8,
                'tensp' => 'Túi Gucci Softbit maxi shoulder',
                'anhsp' => 'frontend/upload/v88NQMeZxGeNozP01CvGVbi2nzKAJRsvmSOq9S3H.jpg',
                'giasp' => 97500000,
                'mota' => 'Chiếc túi đeo vai Gucci Softbit mới tái hiện phần khóa đặc trưng của thương hiệu thành chi tiết Half Horsebit cỡ lớn. Thiết kế này vừa mang tính thẩm mỹ, vừa tiện dụng với phần khóa nam châm và dáng túi mềm mại, được chế tác từ da hạt mềm mại với kết cấu phong phú.\r\n• Da hạt màu taupe (xám nâu nhạt)\r\n• Phụ kiện kim loại tông màu vàng\r\n• Lớp lót microfiber màu nâu đậm\r\n• Bên trong có túi rời có thể tháo ra\r\n• Dây đeo vai rơi xuống: 7.9 inch (~20 cm)\r\n• Kích thước: Rộng 18.1\" x Cao 10.2\" x Sâu 6\" (~46 x 26 x 15 cm)\r\n• Trọng lượng: khoảng 3.1 lbs (~1.4 kg)\r\n• Sản xuất tại Ý\r\n• Đựng vừa iPhone Pro Max/Plus, AirPods, ví dài và son môi\r\n• Khóa nam châm Half Horsebit',
                'giamgia' => 5,
                'giakhuyenmai' => 92625000,
                'soluong' => 7,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 9,
                'tensp' => 'Túi Gucci Diana small',
                'anhsp' => 'frontend/upload/oqkyba439nYcBy0kNPM3Q7AXErPmXXBbxE29dQk1.jpg',
                'giasp' => 97500000,
                'mota' => 'Chiếc túi tote Gucci Diana kết hợp những chi tiết đặc trưng của thương hiệu, như tay cầm tre và phụ kiện kim loại Double G.\r\n• Vải hiệu ứng raffia GG màu nâu tự nhiên\r\n• Viền da màu nâu\r\n• Lớp lót cotton lanh màu nâu\r\n• Phụ kiện kim loại Double G\r\n• Tay cầm bằng tre với độ rơi 3.1 inch (~8 cm)\r\n• Dây đeo vai có thể tháo rời và điều chỉnh với độ rơi 20 inch (~51 cm)\r\n• Trọng lượng: khoảng 0.48kg\r\n• Kích thước: Rộng 7.9\" x Cao 6.3\" x Sâu 3.9\" (~20 x 16 x 10 cm)\r\n• Sản xuất tại Ý\r\n• Đựng vừa iPhone Pro Max/Plus, AirPods, ví nhỏ và son môi',
                'giamgia' => 5,
                'giakhuyenmai' => 92625000,
                'soluong' => 12,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 10,
                'tensp' => 'Túi Gucci Diana small',
                'anhsp' => 'frontend/upload/jDnVStTpLK7WHo0taFowLlDoj99BIEvI3WigMMk2.jpg',
                'giasp' => 130000000,
                'mota' => 'Chiếc túi tote Gucci Diana kết hợp những chi tiết đặc trưng của thương hiệu, như tay cầm tre và phụ kiện kim loại Double G.\r\n• Da đen bóng, đánh bóng\r\n• Phần cứng màu vàng\r\n• Tay cầm bằng tre tráng men với chi tiết bằng đồng thau\r\n• Lớp lót bằng da màu đen\r\n• Đôi G\r\n• Bên trong: 1 túi mở\r\n• thả 3,1\"\r\n• Dây đeo vai bằng da có thể tháo rời và điều chỉnh: dài 18,9\" - 21,7\"; dài 36,6\" - 42,9\"\r\n• Rộng 7,8\" x Cao 6,3\" x Sâu 3,9\"\r\n• Trọng lượng: khoảng 2lbs\r\n• Sản xuất tại Ý\r\n• Phù hợp với iPhone Pro Max/Plus, Airpods, ví dài và son môi',
                'giamgia' => 5,
                'giakhuyenmai' => 123500000,
                'soluong' => 15,
                'id_danhmuc' => 9,
            ],
            [
                'id_sanpham' => 11,
                'tensp' => 'Túi Dioriviera Medium Lady D-Lite',
                'anhsp' => 'frontend/upload/UyHvJx7XY0oaXCcTUuJWBBKlMgtMdUuIxEfvjnL2.jpg',
                'giasp' => 145000000,
                'mota' => 'Tên sản phẩm: Dioriviera Medium Lady D-Lite Bag\r\nGiá: 145.000.000\r\nMô tả: Là một phần của bộ sưu tập giới hạn Dioriviera, túi Lady D-Lite thể hiện tầm nhìn về sự thanh lịch và vẻ đẹp của nhà mốt Dior.\r\nTinh tế và sang trọng, thiết kế này được thêu toàn bộ với họa tiết Toile de Jouy Palms màu trắng và xanh của nghệ sĩ Pietro Ruffo, tái hiện vẻ đẹp thiên nhiên qua khung cảnh rừng nhiệt đới sống động cùng hệ động vật đa dạng.\r\nPhía trước túi nổi bật với chữ ký Christian Dior Paris, trong khi các charm chữ cái D.I.O.R. bằng kim loại mạ vàng nhạt tô điểm và làm nổi bật phom dáng túi.\r\nTúi đi kèm một quai đeo vai bản to, có thể tháo rời và đảo chiều, được thêu tinh xảo, cho phép bạn xách tay hoặc đeo chéo.\r\nChiếc Lady D-Lite size trung này có thể kết hợp linh hoạt với các thiết kế khác trong dòng Dioriviera.',
                'giamgia' => 3,
                'giakhuyenmai' => 140650000,
                'soluong' => 15,
                'id_danhmuc' => 10,
            ],
            [
                'id_sanpham' => 12,
                'tensp' => 'Túi Mini Dior Caro Bucket',
                'anhsp' => 'frontend/upload/be5Dknu1RMi5IwWF2SS928PlF7U6RUMlDIz3bEe1.jpg',
                'giasp' => 95000000,
                'mota' => 'Ra mắt mùa Thu 2025, túi Dior Caro bucket bag là hiện thân của phong cách hiện đại và thanh lịch.\r\nĐược chế tác từ chất liệu da cừu non màu hồng phấn, nổi bật với kỹ thuật chần bông Macrocannage đặc trưng, thiết kế có ngăn chính dạng túi rút tiện lợi.\r\nTúi có một ngăn nắp phía trước được trang trí bằng logo CD kim loại hoàn thiện ánh vàng cổ điển, đủ sức chứa những vật dụng thiết yếu nhỏ gọn.\r\n\r\nNhờ tay cầm trên có thể tháo rời cùng quai đeo da có thể điều chỉnh và tháo rời, phiên bản túi bucket mini này có thể được xách tay, đeo vai hoặc đeo chéo linh hoạt.\r\n⸻\r\nChi tiết sản phẩm:\r\n • Chất liệu chính: Da cừu non và da bê\r\n • Lót trong bằng da bê\r\n • Logo CD ở mặt trước\r\n • Khóa túi rút\r\n • Ngăn trượt phía trước có nắp từ tính\r\n • Tay cầm da có thể tháo rời\r\n • Dây đeo vai da có thể điều chỉnh và tháo rời\r\n • Tặng kèm túi vải bảo quản (dust bag)\r\n • Sản xuất tại Ý',
                'giamgia' => 2,
                'giakhuyenmai' => 93100000,
                'soluong' => 12,
                'id_danhmuc' => 10,
            ],
            [
                'id_sanpham' => 13,
                'tensp' => 'Small Dior Toujours Vertical Tote',
                'anhsp' => 'frontend/upload/qtcupB8yin34O84QDYsmvFn2jTdHlvnzd4elHtzf.jpg',
                'giasp' => 93000000,
                'mota' => 'Túi tote Dior Toujours dáng đứng nổi bật với thiết kế hiện đại và tính ứng dụng cao.\r\nĐược chế tác từ chất liệu da bê màu be phấn, bề mặt túi nổi bật với họa tiết chần bông Macrocannage tinh tế. Thiết kế sở hữu ngăn trong rộng rãi, lý tưởng để đựng tất cả vật dụng thiết yếu hàng ngày.\r\n\r\nPhần dây da mảnh giúp cố định đồ đạc bên trong, trong khi ký tự “D” của khóa CD Lock có thể xoay để điều chỉnh hai bên thân túi, làm nổi bật phom dáng đặc trưng.\r\nTay cầm da phía trên đi kèm với một quai đeo da có thể tháo rời, cho phép bạn linh hoạt xách tay, đeo vai hoặc đeo chéo.\r\n\r\n⸻\r\n\r\nChi tiết sản phẩm:\r\n • Chất liệu chính: Da bê\r\n • Lót trong bằng da bê\r\n • Khóa kép: dây da luồn mảnh và dây có khóa CD Lock mang dòng chữ Christian Dior Paris\r\n • Charm chữ cái D.I.O.R.\r\n • Ngăn trong để thẻ\r\n • Tay cầm da\r\n • Quai đeo vai da có thể tháo rời\r\n • Tặng kèm túi vải bảo quản (dust bag)\r\n • Sản xuất tại Ý',
                'giamgia' => 3,
                'giakhuyenmai' => 90210000,
                'soluong' => 15,
                'id_danhmuc' => 10,
            ],
            [
                'id_sanpham' => 14,
                'tensp' => 'Túi Mini Lady Dior',
                'anhsp' => 'frontend/upload/j6q9ZazZi1SrG1aZswZQACyHJrKEQTrRX13GEU7P.jpg',
                'giasp' => 145000000,
                'mota' => 'Tên sản phẩm: Mini Lady Dior Bag\r\nGiá: 145.000.000 đồng\r\nMô tả:\r\nTúi Lady Dior là hiện thân trọn vẹn của tầm nhìn về sự thanh lịch và vẻ đẹp tinh tế của nhà mốt Dior.\r\nMang dáng vẻ thanh thoát và sang trọng, thiết kế vượt thời gian này được chế tác từ da cừu non ánh ngọc trai màu latte, nổi bật với họa tiết chần bông Cannage đặc trưng, tạo nên bề mặt vân nổi độc đáo không thể nhầm lẫn.\r\n\r\nCác charm kim loại ánh vàng nhạt mang chữ cái D.I.O.R. tô điểm và làm bừng sáng phom dáng túi.\r\nTúi đi kèm dây đeo vai dạng xích có thể tháo rời, cho phép bạn xách tay hoặc đeo chéo, lý tưởng khi sử dụng trong các dịp trang trọng hoặc buổi tối.\bund\r\n\r\nChi tiết sản phẩm:\r\n • Chất liệu chính: Da cừu non\r\n • Lót trong: Da dê và da cừu\r\n • Dây đeo dạng xích có thể tháo rời\r\n • Ngăn trong có khóa kéo\r\n • Có thể kết hợp với các loại dây đeo thêu thủ công của Dior\r\n • Tặng kèm túi vải bảo quản (dust bag)\r\n • Sản xuất tại Ý',
                'giamgia' => 5,
                'giakhuyenmai' => 137750000,
                'soluong' => 16,
                'id_danhmuc' => 10,
            ],
            [
                'id_sanpham' => 15,
                'tensp' => 'Túi Small Dior Toujours',
                'anhsp' => 'frontend/upload/Me3iTIursqKkauDTdqqVosOSThECPQo7X632ONLb.jpg',
                'giasp' => 99000000,
                'mota' => 'Túi Dior Toujours gây ấn tượng với thiết kế năng động và tính ứng dụng cao.\r\nĐược chế tác từ chất liệu da bê màu latte, nổi bật với đường chần bông Macrocannage đặc trưng, túi sở hữu ngăn chứa rộng rãi cùng túi phụ bên trong đồng bộ, giúp sắp xếp vật dụng thiết yếu một cách gọn gàng.\r\n\r\nDây da mảnh giúp cố định đồ đạc bên trong, trong khi chi tiết chữ “D” trong khóa CD Lock có thể xoay để điều chỉnh phom dáng hai bên túi, tạo hiệu ứng thị giác hài hòa và tinh tế.\r\nTay cầm da phía trên có thể điều chỉnh độ dài thông qua các lỗ nhỏ, giúp bạn dễ dàng xách tay một cách thoải mái và linh hoạt.\r\n\r\n⸻\r\n\r\nChi tiết sản phẩm:\r\n • Chất liệu chính: Da bê\r\n • Lót trong: Da lộn bò và da bê\r\n • Khóa kép: Dây da luồn mảnh và dây có khóa CD Lock khắc dòng chữ Christian Dior Paris\r\n • Charm chữ cái D.I.O.R.\r\n • Túi phụ bên trong có thể tháo rời\r\n • Tay cầm da có thể điều chỉnh\r\n • Tặng kèm túi vải bảo quản (dust bag)\r\n • Sản xuất tại Ý',
                'giamgia' => 5,
                'giakhuyenmai' => 94050000,
                'soluong' => 12,
                'id_danhmuc' => 10,
            ],
            [
                'id_sanpham' => 16,
                'tensp' => 'Túi Small Dior Caro Backpack',
                'anhsp' => 'frontend/upload/qULZzX97Vjgm7hPm48zZBduhRYvBCgdvtNYg3DPt.jpg',
                'giasp' => 94000000,
                'mota' => 'Mang đậm tinh thần hiện đại và thanh lịch, ba lô Dior Caro là lựa chọn hoàn hảo cho phong cách năng động mà vẫn giữ nét thời thượng.\r\nĐược chế tác từ chất liệu da cao cấp (thường là da bê hoặc da cừu non), thiết kế nổi bật với họa tiết Macrocannage chần bông đặc trưng của nhà Dior, tạo nên diện mạo sang trọng nhưng trẻ trung.\r\n\r\nTúi có kích thước nhỏ gọn nhưng đủ sức chứa những vật dụng cần thiết hàng ngày. Phần nắp túi được tô điểm bằng khóa kim loại CD ánh vàng cổ điển – biểu tượng đặc trưng của dòng Dior Caro.\r\n\r\nQuai đeo có thể điều chỉnh, giúp bạn linh hoạt sử dụng như đeo lưng, đeo vai hoặc xách tay tùy hoàn cảnh.\r\n\r\n⸻\r\n\r\nChi tiết sản phẩm (mô tả mẫu chuẩn):\r\n • Chất liệu chính: Da bê hoặc da cừu non\r\n • Họa tiết chần bông Macrocannage\r\n • Nắp túi có khóa CD ánh vàng cổ điển\r\n • Dây đeo vai có thể điều chỉnh độ dài\r\n • Ngăn trong rộng rãi + ngăn phụ nhỏ\r\n • Logo Christian Dior Paris dập chìm hoặc in bên trong\r\n • Tặng kèm túi vải bảo quản (dust bag)\r\n • Sản xuất tại Ý',
                'giamgia' => 5,
                'giakhuyenmai' => 89300000,
                'soluong' => 10,
                'id_danhmuc' => 10,
            ],
            [
                'id_sanpham' => 17,
                'tensp' => 'Ví cầm tay da Togo – Pouch in Togo Calfskin',
                'anhsp' => 'frontend/upload/SyNnlT1ab3vFbH9Zgqib3CN892mUK3BVsIT9x6WY.jpg',
                'giasp' => 245000000,
                'mota' => 'Ví cầm tay da Togo – Pouch in Togo Calfskin\r\nChất liệu cao cấp, thiết kế tinh tế – chiếc ví cầm tay này là lựa chọn hoàn hảo cho phong cách hiện đại, thanh lịch và tiện dụng.\r\n • Chất liệu: Da bê Togo – nổi bật với độ bền cao, mềm mại, vân da tự nhiên\r\n • Ngăn chứa: Có ngăn riêng để đựng danh thiếp\r\n • Phụ kiện đi kèm: Dây đeo tay (lanyard) có thể tháo rời\r\n • Cách sử dụng: Có thể cầm tay hoặc đeo ở cổ tay\r\n • Xuất xứ: Sản xuất tại Pháp\r\n • Phần kim loại: Mạ Palladium (bóng, chống gỉ, sang trọng)\r\n • Kích thước:\r\n • Dài: 10 inch (~25,4 cm)\r\n • Cao: 7.9 inch (~20 cm)\r\n • Rộng: 1.6 inch (~4 cm)',
                'giamgia' => 2,
                'giakhuyenmai' => 240100000,
                'soluong' => 10,
                'id_danhmuc' => 11,
            ],
            [
                'id_sanpham' => 18,
                'tensp' => 'Túi Herbag Zip cabine',
                'anhsp' => 'frontend/upload/gTf4u7ho67xBeqGuPZ7IOUZg649H1nO9NzzcSNoB.jpg',
                'giasp' => 123750000,
                'mota' => 'Chất liệu: Thân túi làm từ vải canvas Militaire kết hợp với da bò Hunter cao cấp.\r\n • Khóa: Sử dụng khóa Clou de Selle đặc trưng của Hermès.\r\n • Ngăn chứa:\r\n • Ngăn chính rộng rãi, phù hợp để đựng laptop và các vật dụng cần thiết.\r\n • Túi kéo bên trong có thể tháo rời.\r\n • Túi kéo phía sau tiện lợi cho việc cất giữ đồ dùng nhỏ.\r\n • Tay cầm: Có thể gập lại khi không sử dụng.\r\n • Dây đeo: Dây đeo vai có thể điều chỉnh, cho phép đeo chéo hoặc đeo vai.\r\n • Kích thước: Dài 50 cm x Cao 34 cm x Rộng 22.5 cm.\r\n • Hoàn thiện kim loại: Mạ palladium sáng bóng.\r\n • Xuất xứ: Sản xuất tại Pháp.',
                'giamgia' => 2,
                'giakhuyenmai' => 121275000,
                'soluong' => 10,
                'id_danhmuc' => 11,
            ],
            [
                'id_sanpham' => 19,
                'tensp' => 'Túi Garden Party 49 voyage',
                'anhsp' => 'frontend/upload/MGpA5CDlc3AT3xY2J6Vo3jj3VSwS6qb6Idwd6Nmf.jpg',
                'giasp' => 183750000,
                'mota' => '• Chất liệu: Canvas Militaire kết hợp với da bê Negonda cao cấp.\r\n • Khóa: Khóa bấm Clou de Selle đặc trưng của Hermès.\r\n • Ngăn chứa: Một ngăn chính rộng rãi và một túi kéo bên trong.\r\n • Cách mang: Có thể xách tay hoặc đeo vai.\r\n • Hoàn thiện kim loại: Mạ palladium sáng bóng.\r\n • Xuất xứ: Sản xuất tại Pháp.\r\n • Kích thước: Dài 49 cm x Cao 36 cm x Rộng 25 cm (tương đương 19.3” x 14.2” x 9.8”).',
                'giamgia' => 2,
                'giakhuyenmai' => 180075000,
                'soluong' => 10,
                'id_danhmuc' => 11,
            ],
            [
                'id_sanpham' => 20,
                'tensp' => 'Túi Garden Party pockets vertical',
                'anhsp' => 'frontend/upload/2ghzW9L3k8XlETp9LgImtxFxcgMaoFqy8e9R6Pv8.jpg',
                'giasp' => 198750000,
                'mota' => 'Chất liệu: Canvas Militaire kết hợp với da bê Negonda cao cấp\r\n • Kích thước: Dài 33.5 cm x Cao 37 cm x Rộng 18 cm\r\n • Ngăn chứa:\r\n • 1 ngăn chính rộng rãi\r\n • 2 túi bên hông\r\n • 1 túi kéo bên ngoài\r\n • 1 túi kéo bên trong\r\n • Cách mang: Có thể xách tay\r\n • Hoàn thiện kim loại: Mạ palladium sáng bóng\r\n • Xuất xứ: Sản xuất tại Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 194775000,
                'soluong' => 10,
                'id_danhmuc' => 11,
            ],
            [
                'id_sanpham' => 21,
                'tensp' => 'Túi Bolide 1923 - 45 Racing',
                'anhsp' => 'frontend/upload/SIM9lvmvFth2GMntv1BNSOtv97hGyc3MkPASDUNQ.jpg',
                'giasp' => 907500000,
                'mota' => '• Chất liệu: Kết hợp giữa da bê Evergrain, Evercolor và Swift cao cấp.\r\n • Thiết kế: Lấy cảm hứng từ áo khoác mô tô, với họa tiết chữ “H” năng động tượng trưng cho tia sét, thể hiện sự chuyển động và tốc độ.\r\n • Kỹ thuật chế tác: Sử dụng kỹ thuật thêu appliqué và bọc nổi 14 mảnh da, đòi hỏi hơn 30 giờ làm việc thủ công.\r\n • Kích thước: Dài 45 cm x Cao 37 cm x Rộng 23 cm (tương đương 17.7” x 14.6” x 9.1”).\r\n • Hoàn thiện kim loại: Mạ palladium sáng bóng.\r\n • Xuất xứ: Sản xuất tại Pháp.',
                'giamgia' => 2,
                'giakhuyenmai' => 889350000,
                'soluong' => 10,
                'id_danhmuc' => 11,
            ],
            [
                'id_sanpham' => 22,
                'tensp' => 'Túi Chanel Classic mini (vải tweed)',
                'anhsp' => 'frontend/upload/YXUhHMqrAlWS2aw5u8G6HA7kEbhQVijrEQ2EcrtA.jpg',
                'giasp' => 139250000,
                'mota' => '• Chất liệu Vải Tweed & Kim loại mạ vàng\r\n• Màu sắc: Trắng, Xanh dương & Hồng\r\n• Kích thước: 12 x 20 x 6 cm (có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 136465000,
                'soluong' => 15,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 23,
                'tensp' => 'Túi Chanel 25',
                'anhsp' => 'frontend/upload/8HZjYutc7g0fy3rM4ENuLumKjAW8d04eaXru3rGu.jpg',
                'giasp' => 168250000,
                'mota' => '• Chất liệu Da bê hiệu ứng hạt & Kim loại mạ vàng\r\n• Màu sắc: Hồng nhạt\r\n• Kích thước: 30 x 26 x 14cm(có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 164885000,
                'soluong' => 15,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 24,
                'tensp' => 'Túi Camera Case mini',
                'anhsp' => 'frontend/upload/vVHCPBnZq3MWddQJzHiPEMzb0cSuWf5zag6aev0g.jpg',
                'giasp' => 150850000,
                'mota' => '• Chất liệu Da cừu bóng & Kim loại mạ vàng\r\n• Màu sắc: Khaki\r\n• Kích thước: 13 x 19 x 6cm (có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 147833000,
                'soluong' => 16,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 25,
                'tensp' => 'Túi hộp Cruise 2024/25',
                'anhsp' => 'frontend/upload/bNGa3oAv9Fe9hFu78FsHsu6L4GiHY7Kb6xWhT03E.jpg',
                'giasp' => 156650000,
                'mota' => '• Chất liệu Da cừu bóng & Kim loại mạ vàng\r\n• Màu sắc: Trắng\r\n• Kích thước: 16.5 x 9 x 9cm (có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 153517000,
                'soluong' => 15,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 26,
                'tensp' => 'Túi Chanel đeo hông',
                'anhsp' => 'frontend/upload/iFE2Nj9kFvJp7pXLIbiXUnNMVRqxgdCbubxQ3kCR.jpg',
                'giasp' => 142150000,
                'mota' => 'Nằm trong bộ sưu tập Pre-Collection Xuân Hè 2025\r\n• Chất liệu Da cừu bóng & Kim loại mạ vàng\r\n• Màu sắc: Đen\r\n• Kích thước: 15 x 34 x 8cm (có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 139307000,
                'soluong' => 15,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 27,
                'tensp' => 'Túi vanity mini',
                'anhsp' => 'frontend/upload/PO3OY4JQb2uwNABFzk56buMsC2Za1ACD9qCIHhZ4.jpg',
                'giasp' => 142150000,
                'mota' => 'Nằm trong bộ sưu tập Pre-Collection Xuân Hè 2025\r\n• Chất liệu Da cừu bóng, Ngọc trai nhân tạo & Kim loại màu vàng\r\n• Màu sắc: Đen\r\n• Kích thước: 17 x 18 x 7cm (có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 139307000,
                'soluong' => 15,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 28,
                'tensp' => 'Túi Chanel 19',
                'anhsp' => 'frontend/upload/zboQPDmLlZoRKwiDP7EwlVvJ11jNGOGtjLRmDiV3.jpg',
                'giasp' => 181430000,
                'mota' => '• Chất Da cừu bóng, Kim loại mạ vàng, bạc & ruthenium\r\n• Màu sắc: Đen\r\n• Kích thước: 16 x 26 x 9cm (có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 177801400,
                'soluong' => 16,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 29,
                'tensp' => 'Túi Chanel 11.12',
                'anhsp' => 'frontend/upload/DbSJxRPsjxKmmLafgfIOXBnlVXCh2tq0Q6ZvZ2Lc.jpg',
                'giasp' => 273540000,
                'mota' => '• Chất Vải Tweed & Kim loại mạ vàng\r\n• Màu sắc: Xanh dương nhạt & Đen\r\n• Kích thước 15.5 x 25.5 x 6.5cm(có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 268069200,
                'soluong' => 10,
                'id_danhmuc' => 12,
            ],
            [
                'id_sanpham' => 30,
                'tensp' => 'Túi Chanel nắp gập mini',
                'anhsp' => 'frontend/upload/nh0yV31spYEwLqQEISJVL8LkhWcjCEVVxzTuip5w.jpg',
                'giasp' => 185290000,
                'mota' => '• Chất Da bê hiệu ứng bện ánh kim & Kim loại màu vàng kim\r\n• Màu sắc: Silvery\r\n• Kích thước 13 x 19 x 5.5cm(có thể quy đổi sang inch)\r\n• Sản xuất ở Pháp',
                'giamgia' => 2,
                'giakhuyenmai' => 181584200,
                'soluong' => 15,
                'id_danhmuc' => 12,
            ],
        ];

        foreach ($data as $item) {
            SanPham::create($item);
        }
    }
}
