services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # Laravel sẽ được build trong Dockerfile
    startCommand: apache2-foreground
